#include "Engine/Shaders/Private/PostProcessCommon.usf"

float4 MainPS(VS_OUTPUT In) : SV_Target
{
    float2 UV = In.TexCoord;

    float4 SceneColor = SceneTextureLookup(UV, 0);

    float Gray = dot(SceneColor.rgb, float3(0.299, 0.587, 0.114));
    return float4(Gray, Gray, Gray, SceneColor.a);
}

void MyPostProcessPixelShader(out float4 OutColor : SV_Target, in float2 UV : TEXCOORD0)
{
    OutColor = MainPS(UV);
}
